import test from 'node:test';
import assert from 'node:assert/strict';
import { professorConversation } from '../src/story';
import { newSave,parseSave } from '../src/save';
import { grantPokemon } from '../src/pokemon';
import { checkpoint,encodeSave,decodeSave,SaveLibrary } from '../src/save-library';
import { Engine } from '../src/engine';

test('first meeting tells mother and adventure story before offering the starter',()=>{const story=professorConversation(newSave());assert(story.offerStarter);assert(story.pages.join('').includes('엄마한테 이야기는'));assert(story.pages.join('').includes('모험을 시작'));assert(!story.pages.join('').includes('이미 피카츄'));});
test('Pikachu received first gets the greedy joke and blocks every normal starter',()=>{const s=newSave();grantPokemon(s,25);const story=professorConversation(s);assert(story.pages[0].includes('이미 피카츄'));assert(story.pages.join('').includes('엄마한테'));assert(story.pages.join('').includes('욕심쟁이구나, 하하!'));assert(story.pages.join('').includes('안 된단다.'));assert(!story.offerStarter);for(const species of [1,4,7])assert(!grantPokemon(s,species));assert.equal(s.party.length,1);});
test('Pikachu after a starter is acknowledged without another starter grant',()=>{const s=newSave();grantPokemon(s,7);grantPokemon(s,25);const story=professorConversation(s);assert(story.pages[0].includes('이미 피카츄'));assert(!story.offerStarter)});
test('completed introduction is not repeated when reconsidering the starter',()=>{const s=newSave();s.flags.professorIntroHeard=true;const story=professorConversation(s);assert(story.offerStarter);assert(!story.pages.join('').includes('엄마한테'));});
test('three save slots are independent and reset backup keeps the previous party',()=>{const memory=new Map<string,string>();const store={getItem:(k:string)=>memory.get(k)??null,setItem:(k:string,v:string)=>{memory.set(k,v)}};const lib=new SaveLibrary(store,'qa');for(let i=1;i<=3;i++){const s=newSave();grantPokemon(s,[7,4,1][i-1]);lib.write(i,s)}const prior=lib.read(2)!.save;lib.write('backup',prior);assert.deepEqual([1,2,3].map(i=>lib.read(i)!.save.party[0].species),[7,4,1]);assert.equal(lib.read('backup')!.save.party[0].species,4);assert.equal(new SaveLibrary(store,'separate-qa').read(1),null);});
test('export/import roundtrip retains position, Pikachu and dialogue flags; raw saves also load',()=>{const s=newSave();s.map='lab';s.player={x:9,y:5,facing:'up'};grantPokemon(s,25);s.flags.assistantTalks=4;s.flags.professorIntroHeard=true;const result=decodeSave(encodeSave(s));assert.deepEqual(result?.save,s);assert.deepEqual(decodeSave(JSON.stringify(s))?.save,s);});
test('malformed and unsupported files do not become loadable',()=>{for(const raw of ['null','{}','{','x'.repeat(262145),JSON.stringify({format:'first-partner-save',save:null})])assert.equal(decodeSave(raw),null);const s=newSave();grantPokemon(s,25);for(const invalid of [null,'19',-1,100]){const copy=JSON.parse(JSON.stringify(s));copy.party[0].hp=invalid;assert.equal(parseSave(JSON.stringify(copy)),null)}const future={...s,worldRevision:999};assert.equal(decodeSave(JSON.stringify(future)),null);});
test('saving during a door transition produces the arrival map, not a stuck door tile',()=>{const s=newSave();s.map='town';s.player={x:10,y:9,facing:'up'};const copy=checkpoint(s);assert.equal(copy.map,'lab');assert.deepEqual(copy.player,{x:6,y:11,facing:'up'});assert.equal(s.map,'town');assert(decodeSave(encodeSave(s)));});
test('restoring during movement or a menu clears pending state and cancels the old warp',()=>{const g=new Engine();g.press('ArrowRight');g.panel='starters';g.transition=.3;let oldWarpRan=false;g.transitionWarp=()=>{oldWarpRan=true};g.restore(newSave());for(let i=0;i<15;i++)g.update(.04);assert.equal(g.panel,'field');assert.equal(g.dialogue,null);assert.equal(g.move,null);assert.equal(g.transition,0);assert.equal(oldWarpRan,false);assert.deepEqual(g.save.player,{x:6,y:6,facing:'down'});});
