import type { Engine } from './engine';
import { SPECIES } from './pokemon';
import type { GameMap } from './types';
import type { TourOutdoors } from './explore-outdoors';
const SLOT='canalaveWorkPartnerSlot',MON='canalaveWorkPartner',CARGO='canalaveCargoObserved',REST='canalaveRestObserved',DONE='canalaveWorkCompared';
const CARGO_EVENT='canalaveCargoYard',REST_EVENT='canalavePartnerRestYard';
const selected=(g:Engine)=>{const i=g.save.flags[SLOT],p=typeof i==='number'?g.save.party[i]:undefined;return p&&p.species===g.save.flags[MON]?p:undefined;};
const role=(species:number)=>{const types=SPECIES[species].types;return types.includes('격투')||types.includes('강철')?'무거운 화물 옆에서 작업자 신호 확인':types.includes('물')?'계류 수면과 젖은 바닥의 안전선 확인':types.includes('전기')?'신호등과 기록 장치 주변 점검':types.includes('비행')?'높은 표식과 부두 바람 방향 확인':'가벼운 표찰과 빈 운반함 확인';};
export function installCanalaveWork(map:GameMap,outdoors:TourOutdoors){for(const [name,event] of [['광물 화물 적치장',CARGO_EVENT],['항만 동료 휴게마당',REST_EVENT]] as const){const o=outdoors.objects.find(x=>x.name===name);if(!o)continue;const old=o.event,cells=new Set(o.cells.map(c=>c.x+','+c.y));o.event=event;for(const p of map.props)if(p.dialogue===old&&cells.has(p.x+','+p.y))p.dialogue=event;}}
export function handleCanalaveWork(g:Engine,event:string):boolean{const s=g.save;
if(s.map==='tour_canalave_hall'&&event==='canalaveCargoBoard'){const p=selected(g);if(p&&s.flags[CARGO]&&s.flags[REST]){s.flags[DONE]=true;g.persist();g.say('포켓몬 화물 작업 기록',[SPECIES[p.species].name+'의 역할과 작업 뒤 휴식 상태를 함께 기록했다.','실제 화물을 지급하거나 옮긴 결과가 아니며 보상·승선 조건과 무관하다.']);return true;}if(!s.party.length){g.say('포켓몬 화물 작업 기록판',['함께 온 동료가 생기면 안전한 항만 보조 역할을 정해 보자.']);return true;}g.say('작업 동료 선택',['건강한 동료 한 마리의 항만 보조 역할을 정하세요.'],undefined,[...s.party.map(p=>({label:SPECIES[p.species].name,action:()=>{if(g.save!==s||s.map!=='tour_canalave_hall'||!s.party.includes(p))return;if(p.hp<=0){g.say('항만 사무소 직원',['지친 동료는 센터에서 먼저 쉬게 해 주세요.']);return;}s.flags[SLOT]=s.party.indexOf(p);s.flags[MON]=p.species;s.flags[CARGO]=s.flags[REST]=s.flags[DONE]=false;g.persist();g.say('포켓몬 화물 작업 기록',[SPECIES[p.species].name+'의 역할: '+role(p.species),'외부 적치장과 동료 휴게마당을 차례로 살펴보자.']);}})),{label:'돌아가기',action:()=>{}}]);return true;}
if(s.map!=='tour_canalave'||(event!==CARGO_EVENT&&event!==REST_EVENT))return false;const p=selected(g);if(!p){g.say('항만 생활 지점',['항만 사무소의 작업 기록판에서 동료를 먼저 골라 보자.']);return true;}if(p.hp<=0){g.say('항만 생활 지점',[SPECIES[p.species].name+'은 지쳐 있다. 센터에서 쉬게 하자.']);return true;}const key=event===CARGO_EVENT?CARGO:REST;s.flags[key]=true;s.flags[DONE]=false;g.persist();g.say(event===CARGO_EVENT?'광물 화물 적치장':'항만 동료 휴게마당',[event===CARGO_EVENT?SPECIES[p.species].name+'와 안전선 밖에서 표찰·화물 간격·작업자 신호를 살폈다.':SPECIES[p.species].name+'와 물을 마시고 발과 몸 상태를 확인하며 교대 휴식을 지켰다.',s.flags[CARGO]&&s.flags[REST]?'두 지점을 모두 살폈다. 사무소 기록판에서 비교하자.':'다른 생활 지점도 살펴보자.']);return true;}
