import type { GameMap,Point,Warp } from './types';
import type { Furnishing,TourInterior } from './explore-interiors';
type FloorInfo=Record<string,{floor:number;total:number;title:string}>;
const ids=()=>['tour_canalave_center','tour_canalave_hall','tour_canalave_mart',...['tour_canalave_home1','tour_canalave_home2'].flatMap(id=>[id,id+'_2f',id+'_3f'])];
const size=(id:string):Point=>id.endsWith('_center')?{x:28,y:22}:id.endsWith('_hall')?{x:28,y:24}:id.endsWith('_mart')?{x:24,y:20}:{x:24,y:18};
const positions=(id:string):Point[]=>id.endsWith('_center')?[{x:4,y:8},{x:20,y:8},{x:4,y:15},{x:19,y:15}]:id.endsWith('_hall')?[{x:4,y:7},{x:19,y:7},{x:4,y:16},{x:18,y:16}]:id.endsWith('_mart')?[{x:3,y:9},{x:18,y:9},{x:3,y:15},{x:16,y:15}]:[{x:3,y:6},{x:17,y:6},{x:3,y:12},{x:17,y:12}];
const detail=(kind:Furnishing['kind'],name:string,text:string,event:string):Furnishing=>({kind,name,pages:[text],x:0,y:0,w:3,h:2,event});
const additions:Record<string,Furnishing>={
  tour_canalave_center:detail('bench','항만 동료 회복 대기석','화물 작업과 긴 이동을 마친 포켓몬이 회복 순서를 기다리는 낮은 자리다.','canalaveCenterPartnerBench'),
  tour_canalave_hall:detail('chart','포켓몬 화물 작업 기록판','동료의 몸집과 상태에 맞춰 운반·신호·휴식 역할을 나눈 기록이다.','canalaveCargoBoard'),
  tour_canalave_mart:detail('workbench','항해 준비 정리대','몬스터볼과 상처약, 마른 수건을 일반 도보 여행과 조사선 준비로 나눈다.','canalaveMartPacking'),
};
function warps(id:string,map:GameMap,w:number,h:number,floors:FloorInfo):Warp[]{const info=floors[id],c=Math.floor(w/2),s=w-5;return map.warps.map(x=>{const target=floors[x.to];if(!target)return {...x,x:c,y:h-1};return target.floor>info.floor?{...x,x:s,y:8,spawn:{x:s,y:h-5}}:{...x,x:s,y:h-6,spawn:{x:s,y:9}};});}
export function installCanalaveInteriors(maps:Record<string,GameMap>,rooms:Record<string,TourInterior>,spawns:Record<string,Point>,floors:FloorInfo){for(const id of ids()){const map=maps[id],room=rooms[id];if(!map||!room)continue;if(additions[id])room.objects.push(additions[id]);if(id.includes('_home')){const floor=floors[id]?.floor??1,home=id.includes('home1')?'부두 작업자':'항만 기록원';room.title=home+' 공동주택 '+floor+'층';room.greeting=[floor===1?'젖은 작업 장비와 포켓몬의 발을 먼저 닦는 생활층이에요.':floor===2?'화물과 운하 수위를 날짜별로 정리하는 기록층이에요.':'사람과 포켓몬이 교대 뒤 함께 쉬는 층이에요.'];room.objects.push(detail(floor===1?'workbench':floor===2?'chart':'bench',floor===1?'동료 작업 장비대':floor===2?'운하 교대 기록':'포켓몬 공동 휴게석',floor===1?'몸집에 맞춘 장갑과 신호 조끼, 낮은 물그릇이 놓였다.':floor===2?'운반한 화물과 동료의 휴식 시간을 함께 적었다.':'항구가 보이는 창가에 사람과 포켓몬의 방석이 나란히 놓였다.','canalaveHomeDetail'+id));}
const {x:w,y:h}=size(id),c=Math.floor(w/2),upper=Boolean(floors[id]?.floor&&floors[id].floor>1),rows=Array.from({length:h},(_,y)=>Array.from({length:w},(_,x)=>x>=2&&x<=w-3&&y>=3&&y<=h-3?'.':'#'));if(!upper){rows[h-2][c]='.';rows[h-1][c]='.';}const ps=positions(id);room.objects.forEach((o,i)=>Object.assign(o,ps[i]??ps.at(-1)));room.host={x:c,y:id.endsWith('_center')||id.endsWith('_mart')?5:h-5};if(id.endsWith('_center')||id.endsWith('_mart'))room.reception={x:c-4,y:6,w:8,h:1};const props:GameMap['props']=[];if(room.reception)for(let y=room.reception.y;y<room.reception.y+room.reception.h;y++)for(let x=room.reception.x;x<room.reception.x+room.reception.w;x++){rows[y][x]='#';props.push({x,y,dialogue:id.endsWith('_mart')?'martClerk':'tourHost'});}for(const o of room.objects)for(let y=o.y;y<o.y+o.h;y++)for(let x=o.x;x<o.x+o.w;x++){rows[y][x]='#';props.push({x,y,dialogue:o.event});}const ws=warps(id,map,w,h,floors);for(const x of ws)rows[x.y][x.x]='.';map.width=w;map.height=h;map.walkable=rows.map(r=>r.join(''));map.warps=ws;map.props=props;Object.assign(map.npcs[0],room.host);spawns[id]={x:c,y:h-4};}
for(const warp of maps.tour_canalave.warps){const spawn=spawns[warp.to];if(spawn&&warp.to.startsWith('tour_canalave_'))warp.spawn={...spawn};}}
