import type { Engine } from './engine';
import { SPECIES } from './pokemon';
import type { GameMap } from './types';
import type { TourOutdoors } from './explore-outdoors';
const SLOT='sinnohNorthPartnerSlot',MON='sinnohNorthPartner',LAKE='sinnohNorthLakeObserved',SHELTER='sinnohNorthShelterObserved',CRYSTAL='sinnohNorthCrystalObserved',DONE='sinnohNorthCompared';
const LE='sinnohNorthLakeSurface',SE='sinnohNorthShelterGrove',CE='sinnohNorthCrystalYard';
export function installSinnohNorthObservation(maps:Record<string,GameMap>,outdoors:Record<string,TourOutdoors>){for(const [id,name,event] of [['tour_lake','통합 호수 관찰수면',LE],['tour_snowpoint','눈바람 피난림',SE],['tour_snowpoint','얼음결정 관찰뜰',CE]] as const){const map=maps[id],o=outdoors[id]?.objects.find(x=>x.name===name);if(!map||!o)continue;const old=o.event,cells=new Set(o.cells.map(c=>c.x+','+c.y));o.event=event;for(const p of map.props)if(p.dialogue===old&&cells.has(p.x+','+p.y))p.dialogue=event;}}
export function handleSinnohNorthObservation(g:Engine,event:string):boolean{const s=g.save,chosen=()=>{const i=s.flags[SLOT],p=typeof i==='number'?s.party[i]:undefined;return p&&p.species===s.flags[MON]?p:undefined;};
if(s.map==='tour_lake_hall'&&event==='lakeIdentityGuide'){const p=chosen();if(p&&s.flags[LAKE]&&s.flags[SHELTER]&&s.flags[CRYSTAL]){s.flags[DONE]=true;g.persist();g.say('호수·설원 관찰 기록',[SPECIES[p.species].name+'와 호수 물결, 피난림의 눈자국, 얼음결정 뜰을 비교했다.','정사 세 호수 조사나 신전 사건 완료 기록은 아니다.']);return true;}if(!s.party.length){g.say('세 호수 구분 안내판',['동료가 생기면 호수와 선단 환경을 비교해 보자.']);return true;}g.say('관찰 동료',['세 지점을 함께 살펴볼 건강한 동료를 고르세요.'],undefined,[...s.party.map(p=>({label:SPECIES[p.species].name,action:()=>{if(g.save!==s||s.map!=='tour_lake_hall'||!s.party.includes(p))return;if(p.hp<=0){g.say('안내원',['센터에서 먼저 쉬게 해 주세요.']);return;}s.flags[SLOT]=s.party.indexOf(p);s.flags[MON]=p.species;s.flags[LAKE]=s.flags[SHELTER]=s.flags[CRYSTAL]=s.flags[DONE]=false;g.persist();g.say('관찰 기록',[SPECIES[p.species].name+'와 호수 수면, 선단 피난림과 결정 뜰을 살펴보자.']);}})),{label:'돌아가기',action:()=>{}}]);return true;}
const key=event===LE?LAKE:event===SE?SHELTER:event===CE?CRYSTAL:null;if(!key||!((s.map==='tour_lake'&&event===LE)||(s.map==='tour_snowpoint'&&(event===SE||event===CE))))return false;const p=chosen();if(!p){g.say('관찰 지점',['신오 호수 쉼터 안내판에서 동료를 먼저 골라 보자.']);return true;}if(p.hp<=0){g.say('관찰 지점',[SPECIES[p.species].name+'은 지쳐 있다. 가까운 센터에서 쉬게 하자.']);return true;}s.flags[key]=true;s.flags[DONE]=false;g.persist();const all=s.flags[LAKE]&&s.flags[SHELTER]&&s.flags[CRYSTAL],title=event===LE?'통합 호수 관찰수면':event===SE?'눈바람 피난림':'얼음결정 관찰뜰',text=event===LE?'데크에서 물결과 수초 방향을 살폈다. 물에 들어가거나 포획하지 않았다.':event===SE?'나무 사이 눈자국과 바람 방향을 살폈다.':'눈 결정과 녹은 자국을 살폈다. 신전 석주를 조작하지 않았다.';g.say(title,[SPECIES[p.species].name+'와 '+text,all?'세 지점을 모두 살폈다. 호수 쉼터에서 비교하자.':'남은 지점도 찾아보자.']);return true;}
