import type { Furnishing,TourInterior } from './explore-interiors';
import type { TourOutdoors } from './explore-outdoors';
import type { GameMap,Point } from './types';
import { openRoute211Trails,openCoronet211SurveyTrails } from './sinnoh-route211-trails';
import { openRoute210Habitat } from './sinnoh-route210-habitat';
import type { Place,TourBuilding,TourFeature,TourId } from './explore-world';
export const R211W='tour_sinnoh_route_211_west' as TourId,C211='tour_coronet_211_pass' as TourId,R211E='tour_sinnoh_route_211_east' as TourId,CELESTIC='tour_celestic' as TourId,R210N='tour_sinnoh_route_210_north' as TourId,CELESTIC_RUINS='tour_celestic_ruins' as TourId;
export const CELESTIC_CENTER='tour_celestic_center' as TourId,CELESTIC_SHOP='tour_celestic_shop' as TourId,CELESTIC_HOME='tour_celestic_home' as TourId;
type World={places:Place[];maps:Record<TourId,GameMap>;passagePlaces:Record<string,Place>;spawns:Record<TourId,Point>;features:Record<string,TourFeature[]>;edges:[TourId,TourId][];outdoors:Record<string,TourOutdoors>;rooms:Record<string,TourInterior>;roomParents:Record<string,Place>;buildings:Record<string,TourBuilding[]>};
const open=(r:string[][],x:number,y:number,w:number,h:number)=>{for(let j=y;j<y+h;j++)for(let i=x;i<x+w;i++)r[j][i]='.'};
const horizontal=(w:number,h:number)=>{const r=Array.from({length:h},()=>Array<string>(w).fill('#'));open(r,1,Math.floor(h/2)-2,w-2,5);open(r,Math.floor(w/2)-3,4,6,h-8);return r};
function celesticRoom(id:TourId,name:string,w:number,h:number,to:TourId,spawn:Point,style:TourInterior['style'],hostName:string,dialogue:string,objects:Furnishing[]):{map:GameMap;room:TourInterior;spawn:Point}{
 const x=Math.floor(w/2),r=Array.from({length:h},(_,y)=>Array.from({length:w},(_,i)=>i>=2&&i<=w-3&&y>=3&&y<=h-3?'.':'#')),props:GameMap['props']=[];r[h-2][x]=r[h-1][x]='.';
 const reception=style==='center'||style==='shop'?{x:x-4,y:6,w:8,h:1}:undefined;if(reception)for(let y=reception.y;y<reception.y+reception.h;y++)for(let i=reception.x;i<reception.x+reception.w;i++){r[y][i]='#';props.push({x:i,y,dialogue});}
 for(const o of objects)for(let y=o.y;y<o.y+o.h;y++)for(let i=o.x;i<o.x+o.w;i++){r[y][i]='#';props.push({x:i,y,dialogue:o.event});}
 // The shop has no center reception renderer. Register its existing blocked
 // counter as a furnishing so its visible footprint matches the sales props.
 if(id===CELESTIC_SHOP&&reception)objects.push({...reception,kind:'workbench',name:'봉신 생활 상점 판매대',event:dialogue,pages:['여행에 필요한 도구를 고르는 판매대다.']});
 const room:TourInterior={style,title:name,host:{x,y:5},...(reception?{reception}:{}),objects,greeting:[name+'입니다.','봉신마을의 길과 포켓몬 생활을 천천히 살펴보세요.']};
 return {room,spawn:{x,y:h-4},map:{id,name:'봉신마을 · '+name,width:w,height:h,background:id,walkable:r.map(a=>a.join('')),terrain:[],warps:[{x,y:h-1,to,spawn,entry:'down',facing:'down'}],npcs:[{id:'tourHost',name:hostName,sprite:style==='center'?'pokecenter_nurse':style==='shop'?'old_man':'rancher',x,y:5,facing:'down',dialogue}],props}};
}
export function installSinnohCelesticRoute(a:World){const {places,maps,passagePlaces,spawns,features,edges}=a,e=places.find(p=>p.id==='tour_eterna')!,er=maps[e.id],exit={x:er.width-2,y:32};er.walkable[exit.y]=er.walkable[exit.y].slice(0,exit.x)+'.'+er.walkable[exit.y].slice(exit.x+1);er.warps.push({...exit,to:R211W,spawn:{x:3,y:12},entry:'right',facing:'right'});
 const add=(id:TourId,name:string,w:number,h:number,from:GameMap['id'],to:GameMap['id'])=>{const r=horizontal(w,h),y=Math.floor(h/2);maps[id]={id,name,width:w,height:h,background:id,walkable:r.map(x=>x.join('')),terrain:[],warps:[{x:1,y,to:from,spawn:{x:2,y:2},entry:'left',facing:'left'},{x:w-2,y,to,spawn:{x:2,y:2},entry:'right',facing:'right'}],npcs:[],props:[]};spawns[id]={x:3,y};};
 add(R211W,'신오 211번도로 · 서부',48,24,e.id,C211);maps[R211W].warps[0].spawn={x:er.width-3,y:32};maps[R211W].warps[1].spawn={x:3,y:24};maps[R211W].npcs=[{id:'route211WestHiker',name:'211번도로 서부 등산객',sprite:'rancher',x:24,y:13,facing:'up',dialogue:'route211WestHiker'},{id:'route211WestTrainer',name:'211번도로 서부 트레이너',sprite:'worker',x:35,y:13,facing:'left',dialogue:'route211WestTrainer'}];maps[R211W].props=[{x:5,y:9,dialogue:'route211WestSign'},{x:42,y:9,dialogue:'route211WestSign'}];features[R211W]=[{kind:'rocks',x:5,y:4,w:12,h:6,name:'서부 산기슭'},{kind:'garden',x:31,y:14,w:10,h:6,name:'산 입구 풀밭'}];
 add(C211,'천관산 · 211번도로 통과층',56,48,R211W,R211E);maps[C211].warps[0].spawn={x:45,y:12};maps[C211].warps[1].spawn={x:3,y:14};maps[C211].npcs=[{id:'coronet211Guide',name:'천관산 통과 안내원',sprite:'worker',x:27,y:25,facing:'right',dialogue:'coronet211Guide'}];maps[C211].props=[{x:5,y:21,dialogue:'coronet211Sign'},{x:49,y:21,dialogue:'coronet211Sign'},{x:18,y:24,dialogue:'coronet211WestLayer'},{x:37,y:24,dialogue:'coronet211EastLayer'}];features[C211]=[{kind:'rocks',x:4,y:5,w:17,h:14,name:'서쪽 지층'},{kind:'rocks',x:35,y:27,w:16,h:15,name:'동쪽 지층'}];
 add(R211E,'신오 211번도로 · 동부',56,28,C211,CELESTIC);maps[R211E].warps[0].spawn={x:52,y:24};maps[R211E].warps[1].spawn={x:3,y:20};maps[R211E].npcs=[{id:'route211EastWalker',name:'211번도로 동부 여행자',sprite:'school_kid_f',x:28,y:15,facing:'up',dialogue:'route211EastWalker'},{id:'route211EastTrainer',name:'211번도로 동부 트레이너',sprite:'ace_trainer_f',x:39,y:13,facing:'left',dialogue:'route211EastTrainer'}];maps[R211E].props=[{x:5,y:11,dialogue:'route211EastSign'},{x:50,y:11,dialogue:'route211EastSign'}];features[R211E]=[{kind:'rocks',x:6,y:4,w:12,h:7,name:'동부 산 그림자'},{kind:'grove',x:38,y:16,w:11,h:7,name:'봉신 앞 숲'}];
 const t=Array.from({length:40},(_,y)=>Array.from({length:40},(_,x)=>x>=2&&x<=37&&y>=2&&y<=37?'.':'#')),tf:TourFeature[]=[{kind:'rocks',x:4,y:5,w:11,h:10,name:'봉신 석벽'},{kind:'statue',x:17,y:8,w:7,h:6,name:'전승 벽화 앞마당'},{kind:'grove',x:27,y:23,w:8,h:10,name:'동쪽 전승숲'}];for(const f of tf)for(let y=f.y;y<f.y+f.h;y++)for(let x=f.x;x<f.x+f.w;x++)t[y][x]='#';open(t,1,18,38,5);open(t,18,14,5,24);t[14][20]='.';maps[CELESTIC]={id:CELESTIC,name:'봉신마을',width:40,height:40,background:CELESTIC,walkable:t.map(x=>x.join('')),terrain:[],warps:[{x:1,y:20,to:R211E,spawn:{x:52,y:14},entry:'left',facing:'left'},{x:38,y:20,to:R210N,spawn:{x:3,y:18},entry:'right',facing:'right'},{x:20,y:14,to:CELESTIC_RUINS,spawn:{x:12,y:16},entry:'up',facing:'up'}],npcs:[{id:'celesticElder',name:'봉신마을 전승지기',sprite:'rancher',x:17,y:16,facing:'right',dialogue:'celesticElder'},{id:'celesticResident',name:'봉신마을 주민',sprite:'pokemon_breeder_f',x:25,y:23,facing:'up',dialogue:'celesticResident'}],props:[{x:16,y:17,dialogue:'celesticSign'},{x:25,y:17,dialogue:'celesticEastSign'}]};features[CELESTIC]=tf;spawns[CELESTIC]={x:3,y:20};

 // Both old crossroads now have optional returning trails, with the safe road preserved.
 openCoronet211SurveyTrails(maps[C211]);
 maps[C211].terrain=[{kind:'tallGrass',x:37,y:28,w:2,h:4},{kind:'tallGrass',x:18,y:20,w:2,h:2}];
 openRoute211Trails(maps[R211W],'west');
 openRoute211Trails(maps[R211E],'east');
 // Scenery islands lie between the new paths, never across their walking cells.
 features[R211W]=[{kind:'rocks',x:10,y:8,w:9,h:2,name:'서부 산기슭 돌아가는 길'},
  {kind:'rocks',x:31,y:15,w:6,h:3,name:'남쪽 암반과 합류길'}];
 const services=[
  {kind:'center' as const,x:28,y:6,w:7,h:4,door:{x:31,y:9},room:CELESTIC_CENTER},
  {kind:'house' as const,x:5,y:27,w:7,h:4,door:{x:8,y:30},room:CELESTIC_SHOP},
  {kind:'house' as const,x:15,y:27,w:7,h:4,door:{x:18,y:30},room:CELESTIC_HOME},
 ];
 const roomData=[
  celesticRoom(CELESTIC_CENTER,'포켓몬센터',28,22,CELESTIC,{x:31,y:10},'center','간호사','tourHost',[{kind:'chart',name:'봉신 여행 지도',pages:['서쪽 211번도로와 동쪽 210번도로 북부의 귀환 방향을 표시한다.'],x:3,y:10,w:4,h:2,event:'tourCelesticCenterGuide'},{kind:'console',name:'포켓몬 보관 PC',pages:['파티와 PC의 포켓몬을 확인하고 편성할 수 있다.'],x:18,y:10,w:4,h:2,event:'tourPC'},{kind:'bench',name:'안개 길 휴게석',pages:['210번도로를 걸은 사람과 포켓몬이 쉬는 자리다.'],x:3,y:15,w:5,h:2,event:'tourCelesticCenterBench'}]),
  celesticRoom(CELESTIC_SHOP,'노부부의 생활 상점',24,20,CELESTIC,{x:8,y:31},'shop','봉신 상점 할아버지','martClerk',[{kind:'shelf',name:'산길 보급 선반',pages:['현재는 몬스터볼과 상처약을 판매한다.'],x:3,y:10,w:5,h:2,event:'tourCelesticShopShelf'},{kind:'chart',name:'양쪽 도로 주문표',pages:['211번도로와 210번도로 여행자가 찾는 물품을 적었다.'],x:15,y:10,w:5,h:2,event:'tourCelesticShopLedger'}]),
  celesticRoom(CELESTIC_HOME,'전승가의 집',24,20,CELESTIC,{x:18,y:31},'shrine','전승가 집지기','tourHost',[{kind:'shelf',name:'봉신 가족 기록',pages:['산과 호수 전승을 세대별로 정리한 생활 기록이다.'],x:3,y:7,w:5,h:2,event:'tourCelesticFamilyRecord'},{kind:'chart',name:'천관산 옛 지도',pages:['211번도로와 봉신마을 사이 산길을 오래된 선으로 표시했다.'],x:15,y:7,w:5,h:2,event:'tourCelesticFamilyMap'},{kind:'bench',name:'동료 휴게 방석',pages:['마을을 걸은 포켓몬이 가족 곁에서 쉬는 낮은 자리다.'],x:9,y:13,w:6,h:2,event:'tourCelesticFamilyRest'}]),
 ];
 for(const b of services){for(let y=b.y;y<b.y+b.h;y++)for(let x=b.x;x<b.x+b.w;x++)t[y][x]='#';t[b.door.y][b.door.x]='.';maps[CELESTIC].warps.push({...b.door,to:b.room,spawn:roomData.find(d=>d.map.id===b.room)!.spawn,entry:'up',facing:'up'});}
 for(const d of roomData){maps[d.map.id as TourId]=d.map;spawns[d.map.id as TourId]=d.spawn;a.rooms[d.map.id]=d.room;a.roomParents[d.map.id]=passagePlaces[CELESTIC]??{id:CELESTIC,name:'봉신마을',region:'신오',theme:'temple',concept:'천관산 동쪽의 전승 마을',landmark:'봉신 유적',x:4,y:3};}
 maps[CELESTIC].walkable=t.map(x=>x.join(''));a.buildings[CELESTIC]=services; const n=Array.from({length:64},()=>Array<string>(56).fill('#'));open(n,1,16,18,6);open(n,15,12,8,18);open(n,20,25,18,6);open(n,34,25,7,18);open(n,25,39,16,6);open(n,24,42,7,21);maps[R210N]={id:R210N,name:'신오 210번도로 · 북부',width:56,height:64,background:R210N,walkable:n.map(r=>r.join('')),terrain:[{kind:'tallGrass',x:31,y:39,w:7,h:4}],warps:[{x:1,y:18,to:CELESTIC,spawn:{x:36,y:20},entry:'left',facing:'left'},{x:27,y:62,to:'tour_sinnoh_route_210_south',spawn:{x:27,y:27},entry:'down',facing:'down'}],npcs:[{id:'route210NorthWalker',name:'210번도로 북부 여행자',sprite:'ace_trainer_f',x:37,y:30,facing:'left',dialogue:'route210NorthWalker'},{id:'route210NorthTrainer',name:'210번도로 북부 트레이너',sprite:'worker',x:28,y:43,facing:'left',dialogue:'route210NorthTrainer'}],props:[{x:7,y:15,dialogue:'route210NorthSign'},{x:31,y:47,dialogue:'route210NorthFogSign'}]};openRoute210Habitat(maps[R210N]);features[R210N]=[{kind:'grove',x:4,y:4,w:12,h:9,name:'봉신 동쪽 숲'},{kind:'rocks',x:40,y:12,w:11,h:18,name:'북부 절벽'},{kind:'grove',x:7,y:37,w:13,h:17,name:'안개 낀 나무길'}];spawns[R210N]={x:3,y:18};const s=maps['tour_sinnoh_route_210_south' as TourId],sr=s.walkable.map(r=>r.split(''));open(sr,26,24,3,7);s.walkable=sr.map(r=>r.join(''));s.warps.push({x:28,y:27,to:R210N,spawn:{x:27,y:60},entry:'right',facing:'right'});
 const fs:Furnishing[]=[{kind:'altar',name:'세 호수 전승 벽화',pages:['세 개의 문양이 신오의 호수와 오래된 전승을 나타낸다.\n현재 조사는 전설 포획이나 본편 사건을 시작하지 않는다.'],x:8,y:4,w:8,h:3,event:'tourCelesticRuinsMural'},{kind:'chart',name:'봉신 전승 기록',pages:['마을과 천관산에서 전해 온 이야기를 시대별로 정리했다.\n오래된부적 전달과 조직 사건은 아직 열지 않는다.'],x:3,y:9,w:5,h:3,event:'tourCelesticRuinsRecord'},{kind:'mineral',name:'천관산 암석 표본',pages:['211번도로 통과층의 밝고 짙은 지층을 나란히 놓았다.'],x:16,y:9,w:5,h:3,event:'tourCelesticRuinsStone'}],rr=Array.from({length:20},(_,y)=>Array.from({length:24},(_,x)=>x>=2&&x<=21&&y>=3&&y<=17?'.':'#'));for(const o of fs)for(let y=o.y;y<o.y+o.h;y++)for(let x=o.x;x<o.x+o.w;x++)rr[y][x]='#';rr[19][12]=rr[18][12]='.';const room:TourInterior={style:'shrine',title:'봉신 유적',host:{x:12,y:12},greeting:['봉신마을이 보존하는 전승 유적입니다.','공개된 벽화와 기록만 살펴볼 수 있습니다.'],objects:fs};maps[CELESTIC_RUINS]={id:CELESTIC_RUINS,name:'봉신마을 · 봉신 유적',width:24,height:20,background:CELESTIC_RUINS,walkable:rr.map(r=>r.join('')),terrain:[],warps:[{x:12,y:19,to:CELESTIC,spawn:{x:20,y:15},entry:'down',facing:'down'}],npcs:[{id:'tourHost',name:'봉신 유적 기록원',sprite:'old_man',x:12,y:12,facing:'down',dialogue:'tourHost'}],props:fs.flatMap(o=>Array.from({length:o.h},(_,j)=>Array.from({length:o.w},(_,i)=>({x:o.x+i,y:o.y+j,dialogue:o.event}))).flat())};a.rooms[CELESTIC_RUINS]=room;a.buildings[CELESTIC].push({kind:'landmark',x:17,y:8,w:7,h:7,door:{x:20,y:14},room:CELESTIC_RUINS});spawns[CELESTIC_RUINS]={x:12,y:16};
 for(const [id,name,theme] of [[R211W,'211번도로 서부','mine'],[C211,'천관산 211 통과층','cave'],[R211E,'211번도로 동부','mine'],[CELESTIC,'봉신마을','temple'],[R210N,'210번도로 북부','forest']] as const)passagePlaces[id]={id,name,region:'신오',theme,concept:name,landmark:name,x:4,y:3};passagePlaces[CELESTIC]={...passagePlaces[CELESTIC],concept:'천관산 동쪽의 돌담과 오래된 벽화를 지키는 마을',landmark:'봉신 유적'};passagePlaces[CELESTIC_RUINS]={...passagePlaces[CELESTIC],id:CELESTIC_RUINS,name:'봉신 유적'};a.roomParents[CELESTIC_RUINS]=passagePlaces[CELESTIC];for(const id of [R211W,C211,R211E,CELESTIC,R210N])a.outdoors[id]={objects:[],signs:[]};if(!edges.some(([x,y])=>x===e.id&&y===CELESTIC||x===CELESTIC&&y===e.id))edges.push([e.id,CELESTIC]);}



