import type { GameMap } from './types';import type { Place,TourFeature,TourId } from './explore-world';
export const VERITY_FRONT='tour_verity_lakefront' as TourId,LAKE_VERITY='tour_lake_verity' as TourId,LAKE_VALOR='tour_lake_valor' as TourId,LAKE_ACUITY='tour_lake_acuity' as TourId;
const open=(r:string[][],x:number,y:number,w:number,h:number)=>{for(let j=y;j<y+h;j++)for(let i=x;i<x+w;i++)r[j][i]='.'};
export function installSinnohCanonicalLakes(a:{maps:Record<TourId,GameMap>;passagePlaces:Record<string,Place>;spawns:Record<TourId,{x:number;y:number}>;features:Record<string,TourFeature[]>}){const {maps,passagePlaces,spawns,features}=a,r201=maps.tour_sinnoh_route_201,valor=maps.tour_valor_lakefront,acuity=maps.tour_acuity_lakefront;
 const front=Array.from({length:40},()=>Array<string>(40).fill('#'));open(front,18,20,5,19);open(front,10,18,13,5);open(front,8,8,5,13);open(front,10,6,13,5);features[VERITY_FRONT]=[{kind:'water',x:23,y:5,w:14,h:22,name:'진실호수 수면 전망',description:'201번도로에서 갈라진 호수근처 수면이다.'},{kind:'grove',x:3,y:7,w:7,h:18,name:'진실호수 입구숲',description:'시작 마을 가까이의 조용한 숲이다.'},{kind:'garden',x:5,y:28,w:11,h:7,name:'호숫가 초원',description:'사람과 포켓몬이 쉬는 마른 풀밭이다.'}];maps[VERITY_FRONT]={id:VERITY_FRONT,name:'진실호수 근처',width:40,height:40,background:VERITY_FRONT,walkable:front.map(x=>x.join('')),terrain:[],warps:[{x:20,y:38,to:'tour_sinnoh_route_201',spawn:{x:10,y:7},entry:'down',facing:'down'},{x:20,y:7,to:LAKE_VERITY,spawn:{x:28,y:44},entry:'up',facing:'up'}],npcs:[{id:'verityRanger',name:'진실호수 관리인',sprite:'scientist_f',x:12,y:19,facing:'right',dialogue:'verityRanger'}],props:[{x:17,y:31,dialogue:'veritySign'},{x:23,y:12,dialogue:'verityLakeSign'}]};spawns[VERITY_FRONT]={x:20,y:35};
 const lake=(id:TourId,name:string,back:GameMap['id'],event:string)=>{const r=Array.from({length:48},()=>Array<string>(56).fill('#'));open(r,26,34,5,13);open(r,9,31,39,6);open(r,7,12,6,22);open(r,10,9,36,6);open(r,43,12,6,22);const fs:TourFeature[]=[{kind:'water',x:15,y:16,w:26,h:15,name:name+' 중앙 수면',description:'호수의 생태와 물결을 바라보는 본체 수면이다.'},{kind:'garden',x:23,y:20,w:10,h:8,name:'호수 중앙섬 전망',description:'물 건너 중앙섬을 바라보는 자리다. 섬과 동굴에는 들어갈 수 없다.'},{kind:'grove',x:5,y:36,w:13,h:8,name:'호숫가 방풍림',description:'호수를 찾은 포켓몬이 쉬는 숲 가장자리다.'}];maps[id]={id,name,width:56,height:48,background:id,walkable:r.map(x=>x.join('')),terrain:[],warps:[{x:28,y:46,to:back,spawn:{x:2,y:2},entry:'down',facing:'down'}],npcs:[{id:event+'Keeper',name:name+' 관찰자',sprite:'scientist_f',x:11,y:32,facing:'right',dialogue:event+'Keeper'}],props:[{x:28,y:33,dialogue:event+'Sign'},{x:42,y:30,dialogue:event+'CaveSign'}]};features[id]=fs;spawns[id]={x:28,y:43};};
 lake(LAKE_VERITY,'진실호수',VERITY_FRONT,'verityLake');lake(LAKE_VALOR,'입지호수','tour_valor_lakefront','valorLakeBody');lake(LAKE_ACUITY,'예지호수','tour_acuity_lakefront','acuityLakeBody');maps[LAKE_VERITY].warps[0].spawn={x:20,y:9};maps[LAKE_VALOR].warps[0].spawn={x:29,y:22};maps[LAKE_ACUITY].warps[0].spawn={x:18,y:21};
 r201.walkable[5]=r201.walkable[5].slice(0,10)+'.'+r201.walkable[5].slice(11);r201.warps.push({x:10,y:5,to:VERITY_FRONT,spawn:{x:20,y:35},entry:'up',facing:'up'});valor.walkable[20]=valor.walkable[20].slice(0,29)+'.'+valor.walkable[20].slice(30);valor.warps.push({x:29,y:20,to:LAKE_VALOR,spawn:{x:28,y:43},entry:'up',facing:'up'});acuity.walkable[20]=acuity.walkable[20].slice(0,18)+'.'+acuity.walkable[20].slice(19);acuity.warps.push({x:18,y:20,to:LAKE_ACUITY,spawn:{x:28,y:43},entry:'up',facing:'up'});
 for(const [id,name] of [[VERITY_FRONT,'진실호수 근처'],[LAKE_VERITY,'진실호수'],[LAKE_VALOR,'입지호수'],[LAKE_ACUITY,'예지호수']] as const)passagePlaces[id]={id,name,region:'신오',theme:'water',concept:name+' 생태 관찰 구역',landmark:name,x:4,y:2};}
