import type { GameMap } from './types';
import type { TourInterior } from './explore-interiors';
import type { Place,TourBuilding,TourFeature,TourId } from './explore-world';
export const ROUTE_201='tour_sinnoh_route_201' as TourId,SANDGEM='tour_sandgem' as TourId,ROUTE_202='tour_sinnoh_route_202' as TourId;
export const SANDGEM_CENTER='tour_sandgem_center' as TourId,SANDGEM_LAB='tour_sandgem_lab' as TourId;
const open=(r:string[][],x:number,y:number,w:number,h:number)=>{for(let j=y;j<y+h;j++)for(let i=x;i<x+w;i++)r[j][i]='.'};
const roomMap=(id:TourId,name:string,w:number,h:number,to:TourId,spawn:{x:number;y:number},npc:GameMap['npcs'][number],props:GameMap['props']):GameMap=>{const rows=Array.from({length:h},(_,y)=>Array.from({length:w},(_,x)=>x>=2&&x<=w-3&&y>=3&&y<=h-3?'.':'#'));open(rows,Math.floor(w/2),h-3,1,3);for(const p of props)rows[p.y][p.x]='#';return{id,name,width:w,height:h,background:id,walkable:rows.map(row=>row.join('')),terrain:[],warps:[{x:Math.floor(w/2),y:h-1,to,spawn,entry:'down',facing:'down'}],npcs:[npc],props};};
export function installSinnohOpeningRoute(a:{maps:Record<TourId,GameMap>;passagePlaces:Record<string,Place>;spawns:Record<TourId,{x:number;y:number}>;features:Record<string,TourFeature[]>;buildings:Record<string,TourBuilding[]>;rooms:Record<string,TourInterior>;roomParents:Record<string,Place>}){const {maps,passagePlaces,spawns,features,buildings,rooms,roomParents}=a;
 const r201=Array.from({length:28},()=>Array<string>(64).fill('#'));open(r201,1,13,16,5);open(r201,14,9,14,9);open(r201,25,7,6,13);open(r201,28,16,17,5);open(r201,42,11,6,10);open(r201,45,9,18,5);open(r201,8,5,5,10);open(r201,16,10,8,3);open(r201,32,17,9,3);
 features[ROUTE_201]=[{kind:'garden',x:16,y:10,w:8,h:3,name:'201번도로 첫 풀밭',description:'찌르꼬와 비버니가 사는 첫 선택 풀밭이다.'},{kind:'water',x:4,y:2,w:12,h:6,name:'진실호수근처 방향 물가',description:'북서 분기 너머 진실호수근처로 이어지는 물가다.'},{kind:'grove',x:48,y:17,w:12,h:7,name:'잔모래 방풍림',description:'해안 마을 앞의 낮은 숲이다.'}];maps[ROUTE_201]={id:ROUTE_201,name:'신오 201번도로',width:64,height:28,background:ROUTE_201,walkable:r201.map(x=>x.join('')),terrain:[{kind:'tallGrass',x:16,y:10,w:8,h:3},{kind:'tallGrass',x:32,y:17,w:9,h:3}],warps:[],npcs:[{id:'route201Walker',name:'201번도로 산책객',sprite:'school_kid_f',x:29,y:18,facing:'up',dialogue:'route201Walker'}],props:[{x:5,y:11,dialogue:'route201Sign'},{x:10,y:7,dialogue:'verityApproachSign'},{x:57,y:7,dialogue:'route201Sign'}]};spawns[ROUTE_201]={x:3,y:15};
 const town=Array.from({length:36},(_,y)=>Array.from({length:40},(_,x)=>x>=2&&x<=37&&y>=2&&y<=33?'.':'#'));const tf:TourFeature[]=[{kind:'water',x:3,y:22,w:13,h:9,name:'잔모래 해안',description:'연구 마을 남쪽의 잔잔한 바닷가다.'},{kind:'garden',x:24,y:6,w:10,h:8,name:'연구소 앞 정원',description:'201·202번도로의 포켓몬 생태 자료를 정리하는 뜰이다.'},{kind:'grove',x:27,y:24,w:8,h:7,name:'202번도로 방풍림',description:'북쪽 도로로 나가기 전 쉬는 나무 그늘이다.'}];for(const f of tf)for(let y=f.y;y<f.y+f.h;y++)for(let x=f.x;x<f.x+f.w;x++)town[y][x]='#';const sb:TourBuilding[]=[{kind:'center',x:5,y:7,w:8,h:5,door:{x:9,y:11},room:SANDGEM_CENTER},{kind:'landmark',x:25,y:7,w:8,h:7,door:{x:29,y:13},room:SANDGEM_LAB}];for(const b of sb)for(let y=b.y;y<b.y+b.h;y++)for(let x=b.x;x<b.x+b.w;x++)town[y][x]='#';open(town,18,1,5,34);open(town,8,16,22,5);open(town,2,17,8,4);open(town,9,11,1,6);open(town,29,13,1,4);maps[SANDGEM]={id:SANDGEM,name:'잔모래마을',width:40,height:36,background:SANDGEM,walkable:town.map(x=>x.join('')),terrain:[],warps:[{x:9,y:11,to:SANDGEM_CENTER,spawn:{x:10,y:12},entry:'up',facing:'up'},{x:29,y:13,to:SANDGEM_LAB,spawn:{x:12,y:14},entry:'up',facing:'up'}],npcs:[{id:'sandgemResearcher',name:'잔모래 연구원',sprite:'scientist_f',x:26,y:18,facing:'left',dialogue:'sandgemResearcher'},{id:'sandgemResident',name:'해안 주민',sprite:'pokemon_breeder_f',x:13,y:18,facing:'right',dialogue:'sandgemResident'}],props:[{x:17,y:29,dialogue:'sandgemSign'},{x:24,y:13,dialogue:'sandgemLabSign'},{x:4,y:11,dialogue:'sandgemCenterSign'}]};features[SANDGEM]=tf;buildings[SANDGEM]=sb;spawns[SANDGEM]={x:3,y:18};
 const sandgemPlace:Place={id:SANDGEM,name:'잔모래마을',region:'신오',theme:'village',concept:'해안과 두 첫 도로의 생태를 잇는 연구 마을',landmark:'잔모래 연구소',x:2,y:6};
 rooms[SANDGEM_CENTER]={style:'center',title:'포켓몬센터',host:{x:10,y:5},reception:{x:7,y:6,w:6,h:1},objects:[{kind:'console',name:'포켓몬 보관 PC',pages:['201·202번도로에서 만난 동료를 편성하고 도감을 확인한다.'],x:16,y:5,w:2,h:2,event:'tourExhibit1'},{kind:'bench',name:'해안 여행 대기석',pages:['사람과 포켓몬이 젖은 발을 닦고 쉬는 자리다.'],x:3,y:9,w:4,h:2,event:'tourExhibit2'}],greeting:['잔모래마을 포켓몬센터입니다.','201번도로와 202번도로 사이에서 포켓몬을 회복하고 편성할 수 있어요.']};
 maps[SANDGEM_CENTER]=roomMap(SANDGEM_CENTER,'잔모래마을 · 포켓몬센터',20,16,SANDGEM,{x:9,y:12},{id:'sandgemNurse',name:'간호사',sprite:'pokecenter_nurse',x:10,y:5,facing:'down',dialogue:'nurse'},[{x:7,y:6,dialogue:'nurse'},{x:8,y:6,dialogue:'nurse'},{x:9,y:6,dialogue:'nurse'},{x:10,y:6,dialogue:'nurse'},{x:11,y:6,dialogue:'nurse'},{x:12,y:6,dialogue:'nurse'},{x:16,y:5,dialogue:'tourExhibit1'},{x:3,y:9,dialogue:'tourExhibit2'}]);spawns[SANDGEM_CENTER]={x:10,y:12};
 rooms[SANDGEM_LAB]={style:'lab',title:'잔모래 연구소',host:{x:12,y:5},objects:[{kind:'chart',name:'201번도로 낮 생태표',pages:['찌르꼬와 비버니의 활동 비율을 기록한 표다.'],x:4,y:6,w:3,h:2,event:'sandgemRoute201Record'},{kind:'console',name:'도로 관찰 단말',pages:['보유 중인 201·202번도로 출신 포켓몬 기록을 비교한다.'],x:16,y:6,w:3,h:2,event:'sandgemHabitatConsole'},{kind:'chart',name:'202번도로 여행 지도',pages:['풀밭과 초보 트레이너의 위치를 표시한 지도다.'],x:4,y:11,w:4,h:2,event:'sandgemRoute202Record'}],greeting:['두 첫 도로와 해안의 포켓몬 생활을 비교하는 연구소입니다.']};
 maps[SANDGEM_LAB]=roomMap(SANDGEM_LAB,'잔모래마을 · 연구소',24,18,SANDGEM,{x:29,y:14},{id:'sandgemLabResearcher',name:'잔모래 연구원',sprite:'scientist_f',x:12,y:5,facing:'down',dialogue:'sandgemLabResearcher'},[{x:4,y:6,dialogue:'sandgemRoute201Record'},{x:16,y:6,dialogue:'sandgemHabitatConsole'},{x:4,y:11,dialogue:'sandgemRoute202Record'}]);spawns[SANDGEM_LAB]={x:12,y:14};
 roomParents[SANDGEM_CENTER]=sandgemPlace;roomParents[SANDGEM_LAB]=sandgemPlace;
 const r202=Array.from({length:64},()=>Array<string>(28).fill('#'));open(r202,12,1,5,12);open(r202,9,10,8,14);open(r202,7,21,7,14);open(r202,7,32,15,6);open(r202,17,35,6,13);open(r202,13,45,10,8);open(r202,11,50,7,13);open(r202,4,24,3,8);open(r202,23,39,3,6);open(r202,18,50,5,3);features[ROUTE_202]=[{kind:'garden',x:4,y:24,w:3,h:8,name:'202번도로 첫 풀길',description:'비버니·찌르꼬·꼬링크가 사는 잔모래 북쪽 선택 풀밭이다.'},{kind:'rocks',x:19,y:17,w:7,h:12,name:'202번도로 턱길',description:'축복 방향으로 높아지는 낮은 지형이다.'},{kind:'grove',x:2,y:43,w:9,h:13,name:'축복 남쪽 나무길',description:'도시 입구의 소음을 낮추는 숲이다.'}];maps[ROUTE_202]={id:ROUTE_202,name:'신오 202번도로',width:28,height:64,background:ROUTE_202,walkable:r202.map(x=>x.join('')),terrain:[{kind:'tallGrass',x:4,y:24,w:3,h:8},{kind:'tallGrass',x:23,y:39,w:3,h:6},{kind:'tallGrass',x:18,y:50,w:5,h:3}],warps:[],npcs:[{id:'route202TrainerStarly',name:'202번도로 소년',sprite:'school_kid_m',x:12,y:22,facing:'right',dialogue:'route202TrainerStarly'},{id:'route202TrainerBidoof',name:'202번도로 소녀',sprite:'school_kid_f',x:19,y:37,facing:'left',dialogue:'route202TrainerBidoof'},{id:'route202TrainerBurmy',name:'202번도로 소년',sprite:'school_kid_m',x:15,y:51,facing:'right',dialogue:'route202TrainerBurmy'}],props:[{x:18,y:7,dialogue:'route202Sign'},{x:10,y:56,dialogue:'route202Sign'}]};spawns[ROUTE_202]={x:14,y:3};
 for(const [id,name,theme] of [[ROUTE_201,'신오 201번도로','forest'],[SANDGEM,'잔모래마을','village'],[ROUTE_202,'신오 202번도로','forest']] as const)passagePlaces[id]=id===SANDGEM?sandgemPlace:{id,name,region:'신오',theme,concept:name,landmark:name,x:2,y:6};}
