import type { GameMap } from './types';
import type { Passage } from './journey-world';
import type { Place,TourFeature,TourId } from './explore-world';
export const CORONET_NORTH='tour_coronet_north',ROUTE_216='tour_sinnoh_route_216',ROUTE_217='tour_sinnoh_route_217',ACUITY_LAKEFRONT='tour_acuity_lakefront';
const carve=(r:string[][],x:number,y:number,w:number,h:number)=>{for(let j=y;j<y+h;j++)for(let i=x;i<x+w;i++)r[j][i]='.'};
export function installSinnohNorthRoute(a:{places:Place[];maps:Record<TourId,GameMap>;passages:Record<string,Passage>;passagePlaces:Record<string,Place>;spawns:Record<TourId,{x:number;y:number}>;features:Record<string,TourFeature[]>}){
 const {places,maps,passages,passagePlaces,spawns,features}=a,c=places.find(p=>p.id==='tour_coronet')!,l=places.find(p=>p.id==='tour_lake')!,s=places.find(p=>p.id==='tour_snowpoint')!,legacy='tour_pass_snowpoint_lake' as TourId;
 const cOut=maps[c.id].warps.find(w=>w.to===l.id)!,lBack=maps[l.id].warps.find(w=>w.to===c.id)!,sOut=maps[s.id].warps.find(w=>w.to===legacy)!,legacySnow=maps[legacy].warps.find(w=>w.to===s.id)!;
 const make=(id:string,name:string,w:number,h:number,from:string,to:string,vertical:boolean,npcs:GameMap['npcs'],props:GameMap['props'])=>{const r=Array.from({length:h},()=>Array<string>(w).fill('#'));if(vertical){carve(r,Math.floor(w/2)-2,1,5,h-2);for(let y=9;y<h-8;y+=18)carve(r,y%36===9?6:Math.floor(w/2)-2,y,w-12,5)}else{carve(r,1,Math.floor(h/2)-2,w-2,5);for(let x=14;x<w-12;x+=20)carve(r,x,x%40===14?5:Math.floor(h/2)-2,5,h-10)};maps[id as TourId]={id:id as TourId,name,width:w,height:h,background:id,walkable:r.map(x=>x.join('')),terrain:[],warps:vertical?[{x:Math.floor(w/2),y:1,to:from,spawn:{x:2,y:2},entry:'up',facing:'up'},{x:Math.floor(w/2),y:h-2,to,spawn:{x:2,y:2},entry:'down',facing:'down'}]:[{x:1,y:Math.floor(h/2),to:from,spawn:{x:2,y:2},entry:'left',facing:'left'},{x:w-2,y:Math.floor(h/2),to,spawn:{x:2,y:2},entry:'right',facing:'right'}],npcs,props};spawns[id as TourId]={x:Math.floor(w/2),y:3};};
 make(CORONET_NORTH,'천관산 북부 통과층',56,56,c.id,ROUTE_216,true,[{id:'coronetNorthClimber',name:'북부 등산객',sprite:'rancher',x:26,y:27,facing:'right',dialogue:'coronetNorthClimber'}],[{x:30,y:8,dialogue:'coronetNorthSign'}]);
 make(ROUTE_216,'신오 216번도로',72,32,CORONET_NORTH,ROUTE_217,false,[{id:'route216Hiker',name:'216번도로 등산객',sprite:'rancher',x:35,y:18,facing:'up',dialogue:'route216Hiker'}],[{x:6,y:12,dialogue:'route216Sign'},{x:65,y:12,dialogue:'route216Sign'}]);
 make(ROUTE_217,'신오 217번도로 · 깊은 설원',36,104,ROUTE_216,ACUITY_LAKEFRONT,true,[{id:'route217Traveler',name:'217번도로 설원 여행자',sprite:'ace_trainer_f',x:16,y:52,facing:'right',dialogue:'route217Traveler'}],[{x:20,y:8,dialogue:'route217Sign'},{x:13,y:95,dialogue:'route217Sign'}]);
 make(ACUITY_LAKEFRONT,'예지호수 근처',40,40,ROUTE_217,s.id,true,[{id:'acuityRanger',name:'예지호수 근처 관리인',sprite:'scientist_f',x:18,y:21,facing:'right',dialogue:'acuityRanger'}],[{x:22,y:8,dialogue:'acuitySign'},{x:15,y:31,dialogue:'acuityLakeSign'}]);
 features[CORONET_NORTH]=[{kind:'rocks',x:5,y:8,w:14,h:12,name:'북부 암벽층'},{kind:'rocks',x:35,y:31,w:15,h:14,name:'설원 출구 암반'}];features[ROUTE_216]=[{kind:'rocks',x:20,y:5,w:12,h:8,name:'216 눈절벽'},{kind:'grove',x:48,y:20,w:13,h:7,name:'눈막이 숲'}];features[ROUTE_217]=[{kind:'grove',x:3,y:25,w:10,h:18,name:'217 피난림'},{kind:'rocks',x:23,y:65,w:10,h:20,name:'깊은 눈 표석'}];features[ACUITY_LAKEFRONT]=[{kind:'water',x:4,y:12,w:12,h:14,name:'예지호수 전망'},{kind:'grove',x:25,y:17,w:10,h:14,name:'호숫가 침엽수'}];
 const ps:[[string,string,Place['theme']],[string,string,Place['theme']],[string,string,Place['theme']],[string,string,Place['theme']]]=[[CORONET_NORTH,'천관산 북부 통과층','cave'],[ROUTE_216,'신오 216번도로','snow'],[ROUTE_217,'신오 217번도로 · 깊은 설원','snow'],[ACUITY_LAKEFRONT,'예지호수 근처','snow']];for(const [id,name,theme] of ps)passagePlaces[id]={id:id as TourId,name,region:'신오',theme,concept:name,landmark:name,x:5,y:2};
 passages[ROUTE_216]={id:ROUTE_216 as TourId,a:passagePlaces[CORONET_NORTH],b:passagePlaces[ROUTE_217],kind:'road',bend:7};passages[ROUTE_217]={id:ROUTE_217 as TourId,a:passagePlaces[ROUTE_216],b:passagePlaces[ACUITY_LAKEFRONT],kind:'road',bend:12};
 cOut.to=CORONET_NORTH;cOut.spawn={x:28,y:3};maps[CORONET_NORTH as TourId].warps[0].spawn={...lBack.spawn};maps[CORONET_NORTH as TourId].warps[1].spawn={x:3,y:16};maps[ROUTE_216 as TourId].warps[0].spawn={x:28,y:52};maps[ROUTE_216 as TourId].warps[1].spawn={x:18,y:3};maps[ROUTE_217 as TourId].warps[0].spawn={x:68,y:16};maps[ROUTE_217 as TourId].warps[1].spawn={x:20,y:3};maps[ACUITY_LAKEFRONT as TourId].warps[0].spawn={x:18,y:100};maps[ACUITY_LAKEFRONT as TourId].warps[1].spawn={...legacySnow.spawn};sOut.to=ACUITY_LAKEFRONT;sOut.spawn={x:20,y:36};
}
