import type { GameMap } from './types';
import type { Passage } from './journey-world';
import type { Place,TourFeature,TourId } from './explore-world';
export const R204S='tour_sinnoh_route_204_south' as TourId,RAVAGED='tour_ravaged_path' as TourId,FLOAROMA='tour_floaroma' as TourId,R205S='tour_sinnoh_route_205_south' as TourId;
const open=(r:string[][],x:number,y:number,w:number,h:number)=>{for(let j=y;j<y+h;j++)for(let i=x;i<x+w;i++)r[j][i]='.'};
const vertical=(w:number,h:number)=>{const r=Array.from({length:h},()=>Array<string>(w).fill('#'));open(r,Math.floor(w/2)-2,1,5,h-2);for(let y=10;y<h-8;y+=16)open(r,y%32===10?5:Math.floor(w/2)-2,y,w-10,5);return r};
export function installSinnohFloaromaRoute(a:{places:Place[];maps:Record<TourId,GameMap>;passages:Record<string,Passage>;passagePlaces:Record<string,Place>;spawns:Record<TourId,{x:number;y:number}>;features:Record<string,TourFeature[]>}){const {places,maps,passages,passagePlaces,spawns,features}=a,j=places.find(p=>p.id==='tour_jubilife')!,f=places.find(p=>p.id==='tour_eterna_forest')!,old='tour_sinnoh_route_02' as TourId,jOut=maps[j.id].warps.find(w=>w.to===old)!,fOut=maps[f.id].warps.find(w=>w.to===old)!,oldJ=maps[old].warps.find(w=>w.to===j.id)!,oldF=maps[old].warps.find(w=>w.to===f.id)!;
 const add=(id:TourId,name:string,w:number,h:number,from:GameMap['id'],to:GameMap['id'],npcs:GameMap['npcs'],props:GameMap['props'])=>{const r=vertical(w,h);maps[id]={id,name,width:w,height:h,background:id,walkable:r.map(x=>x.join('')),terrain:[],warps:[{x:Math.floor(w/2),y:h-2,to:from,spawn:{x:2,y:2},entry:'down',facing:'down'},{x:Math.floor(w/2),y:1,to,spawn:{x:2,y:2},entry:'up',facing:'up'}],npcs,props};spawns[id]={x:Math.floor(w/2),y:h-4};};
 add(R204S,'신오 204번도로 · 남부',28,56,j.id,RAVAGED,[{id:'route204Walker',name:'204번도로 산책객',sprite:'school_kid_f',x:12,y:28,facing:'right',dialogue:'route204Walker'}],[{x:16,y:48,dialogue:'route204Sign'},{x:10,y:7,dialogue:'route204Sign'}]);features[R204S]=[{kind:'water',x:2,y:34,w:7,h:13,name:'204 남부 연못'},{kind:'grove',x:18,y:12,w:7,h:15,name:'험한샛길 앞 숲'}];
 add(RAVAGED,'험한샛길 · 통과층',40,40,R204S,FLOAROMA,[{id:'ravagedPathHiker',name:'험한샛길 등산객',sprite:'rancher',x:18,y:20,facing:'right',dialogue:'ravagedPathHiker'}],[{x:22,y:33,dialogue:'ravagedPathSign'},{x:16,y:6,dialogue:'ravagedPathSign'}]);features[RAVAGED]=[{kind:'rocks',x:3,y:8,w:12,h:13,name:'서쪽 갈라진 암벽'},{kind:'rocks',x:25,y:20,w:11,h:13,name:'동쪽 통과 암반'}];
 const t=Array.from({length:40},(_,y)=>Array.from({length:44},(_,x)=>x>=2&&x<=41&&y>=2&&y<=37?'.':'#')),tf:TourFeature[]=[{kind:'garden',x:3,y:5,w:15,h:12,name:'꽃향기 꽃밭'},{kind:'water',x:27,y:23,w:10,h:8,name:'꽃밭 급수 연못'},{kind:'grove',x:29,y:5,w:9,h:12,name:'205 남부 방풍림'}];for(const x of tf)for(let y=x.y;y<x.y+x.h;y++)for(let i=x.x;i<x.x+x.w;i++)t[y][i]='#';open(t,20,1,5,38);open(t,11,18,23,5);maps[FLOAROMA]={id:FLOAROMA,name:'꽃향기마을',width:44,height:40,background:FLOAROMA,walkable:t.map(x=>x.join('')),terrain:[],warps:[{x:22,y:38,to:RAVAGED,spawn:{x:20,y:2},entry:'down',facing:'down'},{x:22,y:1,to:R205S,spawn:{x:16,y:69},entry:'up',facing:'up'}],npcs:[{id:'floaromaGardener',name:'꽃향기 정원사',sprite:'gardener',x:15,y:20,facing:'right',dialogue:'floaromaGardener'},{id:'floaromaResident',name:'꽃밭 주민',sprite:'pokemon_breeder_f',x:29,y:20,facing:'left',dialogue:'floaromaResident'}],props:[{x:19,y:32,dialogue:'floaromaSign'},{x:25,y:6,dialogue:'floaromaSign'}]};features[FLOAROMA]=tf;spawns[FLOAROMA]={x:22,y:35};
 add(R205S,'신오 205번도로 · 남부',32,72,FLOAROMA,f.id,[{id:'route205Worker',name:'205번도로 다리 관리인',sprite:'worker',x:14,y:37,facing:'right',dialogue:'route205Worker'},{id:'route205ForestTrainer',name:'205번도로 숲가 트레이너',sprite:'pokemon_breeder_f',x:22,y:28,facing:'left',dialogue:'route205ForestTrainer'}],[{x:18,y:64,dialogue:'route205Sign'},{x:12,y:7,dialogue:'route205Sign'}]);features[R205S]=[{kind:'water',x:2,y:38,w:9,h:18,name:'205 남부 강'},{kind:'grove',x:21,y:12,w:8,h:20,name:'영원숲 남쪽 나무길'}];
 maps[R204S].warps[0].spawn={...oldJ.spawn};maps[R204S].warps[1].spawn={x:20,y:36};maps[RAVAGED].warps[0].spawn={x:14,y:3};maps[RAVAGED].warps[1].spawn={x:22,y:36};maps[R205S].warps[0].spawn={x:22,y:3};maps[R205S].warps[1].spawn={...oldF.spawn};jOut.to=R204S;jOut.spawn={x:14,y:52};fOut.to=R205S;fOut.spawn={x:16,y:3};
 const ps=[[R204S,'204번도로 남부','forest'],[RAVAGED,'험한샛길 통과층','cave'],[FLOAROMA,'꽃향기마을','flowers'],[R205S,'205번도로 남부','water']] as const;for(const [id,name,theme] of ps)passagePlaces[id]={id,name,region:'신오',theme,concept:name,landmark:name,x:2,y:4};passages[R204S]={id:R204S,a:j,b:passagePlaces[RAVAGED],kind:'road',bend:7};passages[RAVAGED]={id:RAVAGED,a:passagePlaces[R204S],b:passagePlaces[FLOAROMA],kind:'cave',bend:12};passages[R205S]={id:R205S,a:passagePlaces[FLOAROMA],b:f,kind:'road',bend:7};}
