import type { Engine } from './engine';
import { SPECIES } from './pokemon';
const partner=(g:Engine)=>{const i=g.save.flags.sinnohNorthPartnerSlot,p=typeof i==='number'?g.save.party[i]:undefined;return p&&p.species===g.save.flags.sinnohNorthPartner?p:undefined;};
const guide=(g:Engine,origin:string,map:string,event:string)=>()=>{if(g.save.map===origin&&!g.battle)g.setTourDestination(map,event);};
export function handleSinnohNorthLife(g:Engine,event:string):boolean{const m=g.save.map;if(m!=='tour_lake'&&m!=='tour_snowpoint')return false;
if(m==='tour_lake'&&event==='tourResident0'){const p=partner(g),hurt=g.save.party.some(x=>x.hp<x.maxHp);g.say('호수 관찰자',[hurt?'센터에서 동료를 먼저 쉬게 해 주세요.':p?SPECIES[p.species].name+'와 호수와 선단 세 지점을 살펴보세요.':'호수 쉼터 안내판에서 건강한 동료를 골라 보세요.','이곳은 정사 세 호수 중 하나가 아닌 창작 통합 관찰 거점입니다.'],undefined,[{label:'센터',action:guide(g,m,'tour_lake_center','tourExhibit1')},{label:'호수 쉼터',action:guide(g,m,'tour_lake_hall','lakeIdentityGuide')},{label:'관찰수면',action:guide(g,m,'tour_lake','sinnohNorthLakeSurface')},{label:'선단 연결길',action:guide(g,m,'tour_pass_snowpoint_lake','journeySign')},{label:'마치기',action:()=>{}}]);return true;}
if(m==='tour_lake'&&event==='tourResident1'){g.say('설원길 여행자',['현행 길은 통합 호수와 선단을 잇는 축약 설원 통로예요.','원작은 천관산→216번도로→217번도로→예지호수 근처→선단 경로예요. 현재 통로는 그 전체가 아니며 자유 왕복할 수 있어요.'],undefined,[{label:'북쪽 연결길',action:guide(g,m,'tour_pass_snowpoint_lake','journeySign')},{label:'마치기',action:()=>{}}]);return true;}
if(m==='tour_snowpoint'&&event==='tourResident0'){const p=partner(g);g.say('눈길 주민',[p?SPECIES[p.species].name+'와 피난림과 결정 뜰을 살펴보렴.':'남쪽 예지호수 근처에서 설원길이 이어진단다.'],undefined,[{label:'센터',action:guide(g,m,'tour_snowpoint_center','tourExhibit1')},{label:'피난림',action:guide(g,m,'tour_snowpoint','sinnohNorthShelterGrove')},{label:'결정 뜰',action:guide(g,m,'tour_snowpoint','sinnohNorthCrystalYard')},{label:'남쪽 길',action:guide(g,m,'tour_acuity_lakefront','journeySign')},{label:'마치기',action:()=>{}}]);return true;}
if(m==='tour_snowpoint'&&event==='tourResident1'){g.say('신전 방문객',['동쪽 석주는 신전 주변 표식이며 현재 신전 본편이나 관장전이 열린 것은 아니에요.','남쪽은 예지호수 근처·217번도로·216번도로·천관산 북부로 이어져요.'],undefined,[{label:'신전 안내층',action:guide(g,m,'tour_snowpoint_hall','snowpointTempleGuide')},{label:'남쪽 길',action:guide(g,m,'tour_acuity_lakefront','journeySign')},{label:'마치기',action:()=>{}}]);return true;}return false;}
