import type { GameMap,Point,Warp } from './types';
import type { Furnishing,TourInterior } from './explore-interiors';
type FloorInfo=Record<string,{floor:number;total:number;title:string}>;
const ids=()=>['tour_sunyshore_center','tour_sunyshore_mart',...['tour_sunyshore_home1','tour_sunyshore_home2'].flatMap(id=>[id,id+'_2f',id+'_3f']),...'123'.split('').map((_,i)=>i?`tour_sunyshore_hall_${i+1}f`:'tour_sunyshore_hall')];
const size=(id:string):Point=>id.endsWith('_center')?{x:28,y:22}:id.includes('_hall')?{x:28,y:24}:id.endsWith('_mart')?{x:24,y:20}:{x:24,y:18};
const pos=(id:string):Point[]=>id.endsWith('_center')?[{x:4,y:8},{x:20,y:8},{x:4,y:15}]:id.includes('_hall')?[{x:4,y:7},{x:19,y:7},{x:4,y:16}]:id.endsWith('_mart')?[{x:3,y:9},{x:18,y:9},{x:3,y:15}]:[{x:3,y:6},{x:17,y:6},{x:3,y:12}];
const add=(name:string,text:string,event:string):Furnishing=>({kind:'bench',name,pages:[text],x:0,y:0,w:3,h:2,event});
const extra:Record<string,Furnishing>={tour_sunyshore_center:add('해풍 동료 휴게석','해안길을 걸은 동료를 위한 물과 마른 수건이 있다.','sunyshoreCenterRest'),tour_sunyshore_mart:add('해안 여행 정리대','보유 도구와 다음 해안길 준비를 확인하는 자리다.','sunyshoreMartPacking'),tour_sunyshore_hall:add('등대층 안내도','1층 렌즈 · 2층 햇빛/물결 기록 · 3층 전망 휴게.','sunyshoreFloorGuide'),tour_sunyshore_hall_2f:add('동료 빛·물결 관찰 기록판','외부 태양광 설비와 등대 아래 물결을 비교한다.','sunyshoreObservationDesk'),tour_sunyshore_hall_3f:add('등실 동료 전망석','빛에 민감한 동료도 쉴 수 있도록 그늘을 남겼다.','sunyshoreLookoutRest')};
const warps=(id:string,map:GameMap,w:number,h:number,f:FloorInfo):Warp[]=>{const info=f[id],c=Math.floor(w/2),s=w-5;return map.warps.map(x=>{const t=f[x.to];if(!t)return {...x,x:c,y:h-1};return t.floor>info.floor?{...x,x:s,y:8,spawn:{x:s,y:h-5}}:{...x,x:s,y:h-6,spawn:{x:s,y:9}};});};
export function installSunyshoreInteriors(maps:Record<string,GameMap>,rooms:Record<string,TourInterior>,spawns:Record<string,Point>,floors:FloorInfo){for(const id of ids()){const map=maps[id],room=rooms[id];if(!map||!room)continue;if(extra[id])room.objects.push(extra[id]);if(id.includes('_hall')){const floor=floors[id]?.floor??1;room.title=`등대 ${floor}층 · ${floor===1?'렌즈 안내':floor===2?'햇빛과 물결 기록':'등실 전망 휴게'}`;room.greeting=[floor===1?'등대 렌즈와 해안 안내를 살펴보는 층입니다.':floor===2?'도시의 햇빛과 물결을 기록하는 층입니다.':'여행자와 동료가 해안을 바라보며 쉬는 층입니다.'];}if(id.includes('_home')){const floor=floors[id]?.floor??1;room.title=`해안 주민 공동주택 ${floor}층`;room.greeting=[floor===1?'젖은 장비와 동료의 발을 말리는 생활층이에요.':floor===2?'태양광 판과 해풍 기록을 정리하는 층이에요.':'사람과 포켓몬이 함께 쉬는 전망층이에요.'];room.objects.push(add(floor===1?'해안 장비 건조대':floor===2?'햇빛 작업 기록':'동료 전망 방석',floor===1?'수건과 장비를 동료 물품과 나눠 말린다.':floor===2?'빛의 방향과 설비 점검 시간을 적었다.':'등대와 바다가 보이는 낮은 방석이다.',`sunyshoreHome${id}${floor}`));}const {x:w,y:h}=size(id),c=Math.floor(w/2),upper=Boolean(floors[id]&&floors[id].floor>1),rows=Array.from({length:h},(_,y)=>Array.from({length:w},(_,x)=>x>=2&&x<=w-3&&y>=3&&y<=h-3?'.':'#'));if(!upper){rows[h-2][c]='.';rows[h-1][c]='.';}const ps=pos(id);room.objects.forEach((o,i)=>Object.assign(o,ps[i]??ps.at(-1)));room.host={x:c,y:id.endsWith('_center')||id.endsWith('_mart')?5:h-5};if(id.endsWith('_center')||id.endsWith('_mart'))room.reception={x:c-4,y:6,w:8,h:1};const props:GameMap['props']=[];if(room.reception)for(let y=room.reception.y;y<room.reception.y+room.reception.h;y++)for(let x=room.reception.x;x<room.reception.x+room.reception.w;x++){rows[y][x]='#';props.push({x,y,dialogue:id.endsWith('_mart')?'martClerk':'tourHost'});}for(const o of room.objects)for(let y=o.y;y<o.y+o.h;y++)for(let x=o.x;x<o.x+o.w;x++){rows[y][x]='#';props.push({x,y,dialogue:o.event});}const ws=warps(id,map,w,h,floors);for(const x of ws)rows[x.y][x.x]='.';map.width=w;map.height=h;map.walkable=rows.map(r=>r.join(''));map.warps=ws;map.props=props;Object.assign(map.npcs[0],room.host);spawns[id]={x:c,y:h-4};}for(const warp of maps.tour_sunyshore.warps){const spawn=spawns[warp.to];if(spawn&&warp.to.startsWith('tour_sunyshore_'))warp.spawn={...spawn};}}
